# todo :: yml profiles 하나로 합치기

server:
  port: 8080
  servlet:
    context-path: /

spring:
  # todo 개발 데이터베이스 연결
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl_-auto: create
    show-sql: true # console 창에 sql 출력
    properties:
      hibernate:
        format_sql: true # sql 문을 예쁘게 출력
        default_batch_fetch_size: 500 # 일대다 컬렉션 조회 시 성능 최적화
    open-in-view: false # 영속성 컨텍스트의 생존 범위를 트랜잭션 범위로 한정

  servlet:
    multipart:
      max-file-size: 10MB # 파일 업로드 요청 시 하나의 파일 크기를 10MB로 제한
      max-request-size: 100MB # 파일 업로드 요청 시 모든 파일 크기 합을 100MB로 제한

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.type: trace # console 창에서 조건에 바인딩 되는 값 조회 결과 출력
    com.app: debug # todo 패키지 수정

feign:
  client:
    config:
      default:
        connectTimeout: 5000 # 해당 과정을 5초 안에 하지 않으면 connectTimeout error
        readTimeout: 5000 # 연결은 됐는데 요청한 서버에서 응답이 5초 안에 오지 않으면 readTimeout error

kakao:
  client:
    id: ENC(qTWf//LPnqnb62cKO6UmUaWa0WX3dgW7Y+JEYgB5uIbSOPb5iGDQGhawcUX9LxtK) # kakao develop site > 요약정보 > REST API 키
    secret: ENC(TdmXheDIndccclB9DnAiLVK7uSdJ/xrU/FfijDNSSGLeAgT9Rx6JV+i7xvg0KgKa) # kakao develop site > 보안 > 코드

token: # JWT (Json Web Token)
  secret: ENC(JSp5mnTzuhJiHEBwr8ls0frG2wch3HqBsB/QL+YEx4fcYei/bqAC6A==) # 임의의 문자열
  access-token-expiration-time: 900000 # 15분 : 1000(ms) x 60(s) x 15(m)
  refresh-token-expiration-time: 1209600000 # 2주 : 1000(ms) x 60 (s) x 60(m) x 24(h) x 14(d)

jasypt:
  password: ${PASSWORD}